### ISSUE TITLE
container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory

### ISSUE THREAD

**Issue by willzhang** [mgoltzsche/podman-static#54] opened 2023-03-09 17:11 UTC
why podman-static not include catatonit?
```
root@node01:~# podman version
Client:       Podman Engine
Version:      4.4.2
API Version:  4.4.2
Go Version:   go1.18.10
Built:        Thu Jan  1 08:00:00 1970
OS/Arch:      linux/amd64
```

this work
```
curl -sLo /usr/libexec/podman/catatonit https://github.com/openSUSE/catatonit/releases/download/v0.1.7/catatonit.x86_64 
chmod +x /usr/libexec/podman/catatonit
```

**Comment by mgoltzsche** [comment] 2023-03-10 00:02
@willzhang podman-static does not include catatonit because I didn't need it so far.
What is your use-case that requires catatonit to be installed?
Can you provide a reproducible example of your use-case in form of a podman CLI call please?

**Comment by willzhang** [comment] 2023-03-10 04:48
use-case1、cephadm need podman
https://docs.ceph.com/en/latest/cephadm/install/
```
curl --silent --remote-name --location https://github.com/ceph/ceph/raw/quincy/src/cephadm/cephadm
chmod +x cephadm
mv cephadm /usr/local/bin
```
this will give error `container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory `
```
cephadm bootstrap --mon-ip 192.168.10.10
```
use-case2、podman play kube kubernetes.yaml

**Comment by adrecord** [comment] 2023-03-11 02:03
I've gotten around this on machines without catatonit by specifying an infra_image in your containers.conf, in the engine section, like so..

```
[engine]
infra_image="k8s.gcr.io/pause:3.8"
```

See if that works for you @willzhang.

Perhaps this should be the default in the shipped containers.conf, to remove the dependency on catatonit for the kube/pod commands.

**Comment by mgoltzsche** [comment] 2023-03-14 23:59
@adrecord thanks for your suggestion!
@willzhang can you confirm that #55 works for you?

**Comment by willzhang** [comment] 2023-03-15 01:34
i will confirm later

**Comment by cruscio** [comment] 2023-03-20 20:27
@mgoltzsche - looks like you already have a fix, but in case this helps...

> What is your use-case that requires catatonit to be installed?

Here's one: https://github.com/89luca89/distrobox/issues/667  _Distrobox: Installing podman in a static manner_ on a steam deck, `podman pod create` fails. You can find the full debug log in that issue if you're curious. Seems like some recent version of podman changed behavior to building the `pause` image locally by default, which can't be done without `catatonit`.

Meanwhile, I added `infra_image="k8s.gcr.io/pause:3.8"` to `/home/deck/.config/containers/containers.conf`, pulled the image, and reran `podman pod create` - and it worked great!

**Comment by mgoltzsche** [comment] 2023-03-21 01:48
@cruscio thanks for confirming that the fix works. I merged the PR but did not publish it yet. I anticipate there will be a new podman release within the next days which I'll ship the fix with.

**Comment by mgoltzsche** [comment] 2023-03-25 01:57
The fix was released with [v4.4.3](https://github.com/mgoltzsche/podman-static/releases/tag/v4.4.3).

**Comment by willzhang** [comment] 2023-04-02 17:05
> 我已经在没有 catatonit 的机器上解决了这个问题，方法是在引擎部分的 container.conf 中指定一个 infra_image，就像这样......
> 
> ```
> [engine]
> infra_image="k8s.gcr.io/pause:3.8"
> ```
> 
> 看看这是否适合你@willzhang.
> 
> 也许这应该是随附的 container.conf 中的默认设置，以消除 kube/pod 命令对 catatonit 的依赖。

this not work for me
```
root@node01:~# cat  /etc/containers/containers.conf
# See https://github.com/containers/common/blob/master/pkg/config/containers.conf
[engine]
cgroup_manager = "cgroupfs"
events_logger="file"
infra_image="k8s.gcr.io/pause:3.8"

root@node01:~# podman pull k8s.gcr.io/pause:3.8
Trying to pull k8s.gcr.io/pause:3.8...
Getting image source signatures
Copying blob 9457426d6899 done  
Copying config 4873874c08 done  
Writing manifest to image destination
Storing signatures
4873874c08efc72e9729683a83ffbb7502ee729e9a5ac097723806ea7fa13517

root@node01:~# cephadm bootstrap --mon-ip 192.168.72.40
Verifying podman|docker is present...
Verifying lvm2 is present...
Verifying time synchronization is in place...
Unit chrony.service is enabled and running
Repeating the final host check...
podman (/usr/local/bin/podman) version 4.4.3 is present
systemctl is present
lvcreate is present
Unit chrony.service is enabled and running
Host looks OK
Cluster fsid: aac503de-d174-11ed-bad6-d1da98c13f11
Verifying IP 192.168.72.40 port 3300 ...
Verifying IP 192.168.72.40 port 6789 ...
Mon IP `192.168.72.40` is in CIDR network `192.168.72.0/24`
Mon IP `192.168.72.40` is in CIDR network `192.168.72.0/24`
Internal network (--cluster-network) has not been provided, OSD replication will default to the public_network
Pulling container image quay.io/ceph/ceph:v17...
Non-zero exit code 125 from /usr/local/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint ceph --init -e CONTAINER_IMAGE=quay.io/ceph/ceph:v17 -e NODE_NAME=node01 -e CEPH_USE_RANDOM_NONCE=1 quay.io/ceph/ceph:v17 --version
ceph: stderr Error: container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/cephadm", line 9653, in <module>
    main()
  File "/usr/local/bin/cephadm", line 9641, in main
    r = ctx.func(ctx)
  File "/usr/local/bin/cephadm", line 2205, in _default_image
    return func(ctx)
  File "/usr/local/bin/cephadm", line 5664, in command_bootstrap
    image_ver = CephContainer(ctx, ctx.image, 'ceph', ['--version']).run().strip()
  File "/usr/local/bin/cephadm", line 4144, in run
    out, _, _ = call_throws(self.ctx, self.run_cmd(),
  File "/usr/local/bin/cephadm", line 1852, in call_throws
    raise RuntimeError(f'Failed command: {" ".join(command)}: {s}')
RuntimeError: Failed command: /usr/local/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --entrypoint ceph --init -e CONTAINER_IMAGE=quay.io/ceph/ceph:v17 -e NODE_NAME=node01 -e CEPH_USE_RANDOM_NONCE=1 quay.io/ceph/ceph:v17 --version: Error: container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory

root@node01:~# 
```

**Comment by willzhang** [comment] 2023-04-03 02:24
maybe this is cephadm problems, it only find catatonit in /usr/libexec/podman/ ?

**Comment by mgoltzsche** [comment] 2023-04-05 00:10
Looks like the catatonit binary is still required and needs to be shipped with the podman-static image.

(This one is related: https://github.com/containers/common/issues/1110)

**Comment by mgoltzsche** [comment] 2023-04-05 01:12
Unfortunately, the catatonit build failed due to a syntax error within the `./configure` script (see #58). Feel free to fix the PR. Otherwise, I'll revisit that some other evening.

**Closed** 2023-04-07 23:07 UTC

**Comment by mgoltzsche** [comment] 2023-04-08 01:45
I fixed it.
Release [v4.4.4](https://github.com/mgoltzsche/podman-static/releases/tag/v4.4.4) also ships the catatonit binary

**Comment by thesteve0** [comment] 2023-07-14 01:48
Not a bug, just frustrated that SteamDeck pacman only installs 4.2.1

``
`(125)(deck@steamdeck ~)$ podman -v
podman version 4.2.1
```
